############################################################
#
# See http://www.appveyor.com/docs/appveyor-yml for many more options
#
# Credit for a lot of this file goes to RamblingCookieMonster:
# https://github.com/RamblingCookieMonster/PSSQLite/blob/master/appveyor.yml
#
############################################################

# powershell core and 5.1
image:
    - Visual Studio 2017
    - Visual Studio 2019

environment:
  PSGalleryAPIKey:
    secure: UdM6qhf5B0G8liHhUrwWERCZr44iSqmg4jUq0lwlTjZs4KyeoiwnBzdej0phqIAm
  PShell: '5'

version: 1.7.{build}

# Don't rebuild when I tag a release on GitHub
skip_tags: true

# Ignore testing a commit if only the readme changed
# Or if I include "skip-tests" in the commit message
skip_commits:
  message: /skip\-tests/
  files:
    - .github/
    - .vscode/
    - assets/
    - Tools/
    - README.md
    - .gitattributes
    - .gitignore

# PRs, by definition, don't change anything and therefore should not increment the version
# To be fair, this is not important, and is really just AppVeyor enabling my pedantry
pull_requests:
  do_not_increment_build_number: true

install:
    - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
        Install-Module InvokeBuild -Scope CurrentUser -Force
        Install-Module BuildHelpers -Scope CurrentUser -Force
        Install-Module platyPS -Scope CurrentUser -Force
        Install-Module Pester -Scope CurrentUser -Force
        Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
        $env:releasePath = "$($pwd.Path)\Release"

before_build:
    - ps: Invoke-Build -Task ShowDebug

build_script:
    - ps: Invoke-Build -Task Build

test_script:
    - ps: Invoke-Build -Task Test

before_deploy:
    - ps: Invoke-Build -Task Deploy

#Build with powershell core
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      PShell: '7'
    install:
      - pwsh: |
          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
          Install-Module InvokeBuild -Scope CurrentUser -Force
          Install-Module BuildHelpers -Scope CurrentUser -Force
          Install-Module platyPS -Scope CurrentUser -Force
          Install-Module Pester -Scope CurrentUser -Force
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          $env:releasePath = "$($pwd.Path)\Release"
    before_build:
      - pwsh: Invoke-Build -Task ShowDebug
    build_script:
      - pwsh: Invoke-Build -Task Build

    test_script:
      - pwsh: Invoke-Build -Task Test

    before_deploy:
      - pwsh: Invoke-Build -Task Deploy


deploy:
    provider: GitHub
    release: v$(appveyor_build_version)
    description: ''
    auth_token:
        secure: m72Ke3nJcSxZkc36UwRIw+q0NtNvERfQYHZUBNDvLP/kjW+mWmVueR6tmgBujyBM
    draft: false
    prerelease: false
    on:
        branch: master                  # release from master branch only
        appveyor_repo_tag: false        # deploy on tag push only
